### ISSUE TITLE
Module not found? 

### ISSUE THREAD

**Issue by Cosmopup2010** [mrasyidismail/Discord-Bot#2]
I don't know if I am doing something wrong, but when i go to run it, it says module not found. 

Also, when i did the (cp src/config-example.json src/config.json), it said permission denied. i've been making the bot on replit.

![Screenshot 2023-09-18 220027](https://github.com/mrasyidismail/Discord-Bot/assets/145407435/6be4e02d-0c59-493d-9cde-4b313e8434bf)

**Comment by mrasyidismail** [comment]
Permission denied
Try manually copy the `config-example.json` and paste it on `src` folder and rename it to `config.json`.

Module not found:
just `npm run start` on `Discord-Bot` path
![image](https://github.com/mrasyidismail/Discord-Bot/assets/145036850/69711913-637f-472a-8bac-cea7b0fe276b)

Also, for replit. I doubt it'll work since it uses puppeteer, refer to this [#19 - Make the code work on replit](https://github.com/realcoloride/node_characterai/issues/49)

**Comment by Cosmopup2010** [comment]
okay, i copied the file, but i ran the command in shell, nothing happens. as for the npm run start, i did that and it said command not found.

**Comment by mrasyidismail** [comment]
Check if you have installed npm

**Comment by Cosmopup2010** [comment]
nevermind the website i was using. i ran it on my computer instead and this is what happened when i ran it

![Screenshot 2023-09-18 234156](https://github.com/mrasyidismail/Discord-Bot/assets/145407435/0adf167d-7f5d-43e3-9c68-2881a3faeeab)

**Comment by mrasyidismail** [comment]
Did you replace the token on `config.json` with your bot token ?

**Comment by Cosmopup2010** [comment]
i figured it all out. thank you!
